# Generated by Django 6.0 on 2025-12-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.CharField(max_length=20, unique=True)),
                ('proveedor', models.CharField(max_length=100)),
                ('codigo_proveedor', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('posicion', models.CharField(blank=True, max_length=50)),
                ('ubicacion', models.CharField(blank=True, max_length=50)),
                ('lado', models.CharField(blank=True, max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio_desde', models.IntegerField()),
                ('anio_hasta', models.IntegerField()),
                ('version', models.CharField(blank=True, max_length=50)),
                ('marca_prod', models.CharField(max_length=50)),
                ('imagen0', models.URLField(blank=True)),
                ('imagen1', models.URLField(blank=True)),
                ('precio_costo', models.DecimalField(decimal_places=0, max_digits=10)),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
    ]
