# Generated by Django 6.0 on 2026-01-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('supertype', models.CharField(blank=True, max_length=50)),
                ('subtypes', models.JSONField(blank=True, default=list)),
                ('types', models.JSONField(blank=True, default=list)),
                ('hp', models.CharField(blank=True, max_length=10)),
                ('set_id', models.CharField(max_length=50)),
                ('set_name', models.CharField(max_length=100)),
                ('set_series', models.CharField(blank=True, max_length=100)),
                ('set_release_date', models.DateField(blank=True, null=True)),
                ('rarity', models.CharField(blank=True, max_length=50)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('artist', models.CharField(blank=True, max_length=100)),
                ('image_small', models.URLField(blank=True)),
                ('image_large', models.URLField(blank=True)),
                ('price_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_mid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_market', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_currency', models.CharField(default='USD', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'set_release_date'],
            },
        ),
        migrations.CreateModel(
            name='PokemonSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('total_cards', models.IntegerField(default=0)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True)),
                ('symbol_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
    ]
