# Generated by Django 6.0 on 2026-01-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pokemoncard_pokemonset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('resumen', models.TextField(max_length=300)),
                ('contenido', models.TextField()),
                ('imagen', models.URLField(blank=True)),
                ('categoria', models.CharField(choices=[('desarrollo', 'Desarrollo'), ('tecnologia', 'Tecnología'), ('proyecto', 'Proyecto'), ('tutorial', 'Tutorial'), ('noticia', 'Noticia')], default='desarrollo', max_length=20)),
                ('estado', models.CharField(choices=[('idea', 'Idea'), ('desarrollo', 'En Desarrollo'), ('completado', 'Completado'), ('publicado', 'Publicado')], default='publicado', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('publicado', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
