# Generated by Django 6.0 on 2026-01-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_post_activo_alter_post_imagen_alter_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.AddField(
            model_name='post',
            name='fuentes',
            field=models.TextField(blank=True, help_text='Enlaces o bibliografía consultada para el artículo.'),
        ),
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.CharField(blank=True, help_text='Palabras clave separadas por comas.', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_descripcion',
            field=models.CharField(blank=True, help_text='Descripción para buscadores (máx 160 caracteres).', max_length=160),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_titulo',
            field=models.CharField(blank=True, help_text='Título optimizado para Google (máx 70 caracteres).', max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('desarrollo', 'Desarrollo'), ('tecnologia', 'Tecnología'), ('proyecto', 'Proyecto'), ('tutorial', 'Tutorial'), ('noticia', 'Noticia'), ('ia', 'Inteligencia Artificial')], default='desarrollo', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.TextField(help_text='Contenido en formato HTML (procedente del editor enriquecido).'),
        ),
        migrations.AlterField(
            model_name='post',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En Revisión'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], default='publicado', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Imagen Destacada'),
        ),
        migrations.AlterField(
            model_name='post',
            name='resumen',
            field=models.TextField(help_text='Breve introducción para las tarjetas del blog.', max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título del Artículo'),
        ),
    ]
